apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: food-ordering
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: db-credentials
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
            - mountPath: /docker-entrypoint-initdb.d
              name: init-db
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: init-db
          configMap:
            name: postgres-init
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: food-ordering
data:
  init-db.sql: |
    CREATE DATABASE user_service_db;
    CREATE DATABASE restaurant_service_db;
    CREATE DATABASE order_service_db;
    CREATE DATABASE payment_service_db;
    CREATE DATABASE delivery_service_db;
    CREATE DATABASE notification_service_db;
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: food-ordering
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
